ProjectFinalEMDAAdvanced/Models/Leave.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ProjectFinalEMDAAdvanced.Models
{
    public class Leave
    {
        [Key]//Primary key
        public int Id { get; set; }
        public Staff Staff { get; set; }//Staff
        public DateTime StartDate { get; set; }//Startdate
        public DateTime EndDate { get; set; }//Enddate
        public int TotalDays { get; set; }//Total days
        public bool Accepted { get; set; }//Accepted
    }
}

ProjectFinalEMDAAdvanced/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjectFinalEMDAAdvanced.Data;
using ProjectFinalEMDAAdvanced.Models;

namespace ProjectFinalEMDAAdvanced.Controllers
{
    [Authorize]
    public class EventsController : Controller
    {
        private readonly StaffDbContext _context;

        public EventsController(StaffDbContext context)
        {
            _context = context;
        }

        // GET: Events
        public async Task<IActionResult> Index()
        {
            return View(await _context.Events.ToListAsync());
        }

        // GET: Events/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            //if (id == null)
            //{
            //    return NotFound();
            //}

            var events = await _context.Events
                .SingleOrDefaultAsync(m => m.Id == id);
            if (events == null)
            {
                return NotFound();
            }

            return View(events);
        }

        // GET: Events/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Events/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,EventColor,Start,End,Title,IsFullDay,Days,Weeks,Staff")] Events events)
        {
            if (ModelState.IsValid)
            {
                _context.Add(events);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            //if (ModelState.IsValid)
            //{
            //    //check if there is a fullday or repeating weeks or days
            //    if (events.IsFullDay || events.Days > 0 || events.Weeks > 0)
            //    {
            //        foreach (var booking in DayWeeksAllDayMods.EventCalc(events))
            //        {
            //            _context.Add(booking);
            //        }
            //    }
            //    //pass through the event and look for clashes where its the same room after today
            //    DayWeeksAllDayMods.DoTheDatesOverlap(_context.Events.Where(e => e.ResourceId == events.ResourceId && e.End > DateTime.Now).ToList(), events);

            //    //We have a clash
            //    if (DayWeeksAllDayMods.WeHaveAClash == true)
            //    {
            //        return RedirectToAction("Clash");
            //    }
            //    else
            //    {//we dont have a clash
            //        _context.Add(events);
            //        await _context.SaveChangesAsync();
            //        return View();
            //    }
            //}


            return View(events);
        }

        // GET: Events/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var events = await _context.Events.FindAsync(id);
            if (events == null)
            {
                return NotFound();
            }
            return View(events);
        }

        // POST: Events/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,EventColor,Start,End,Title,IsFullDay,Days,Weeks,Staff")] Events events)
        {
            if (id != events.Id)
            {
                //return NotFound();
                events.Id = id;
            }

            if (ModelState.IsValid && events.End > events.Start)
            {
                try
                {
                    _context.Update(events);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventsExists(events.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            //return View(events);
            return RedirectToAction(nameof(Index));
        }

        // GET: Events/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var events = await _context.Events
                .SingleOrDefaultAsync(m => m.Id == id);
            if (events == null)
            {
                return NotFound();
            }

            return View(events);
        }

        // POST: Events/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var events = await _context.Events.FindAsync(id);
            _context.Events.Remove(events);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EventsExists(int id)
        {
            return _context.Events.Any(e => e.Id == id);
        }
    }
}

ProjectFinalEMDAAdvanced/Controllers/LeavesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjectFinalEMDAAdvanced.Data;
using ProjectFinalEMDAAdvanced.Models;

namespace ProjectFinalEMDAAdvanced.Controllers
{
    [Authorize]
    public class LeavesController : Controller
    {
        private readonly StaffDbContext _context;

        public LeavesController(StaffDbContext context)
        {
            _context = context;
        }

        // GET: Leaves
        public async Task<IActionResult> Index()
        {
            List<Leave> StaffNames = new List<Leave>();
            StaffNames.AddRange(_context.Leave
                .Include(s => s.Staff)
                .ToList());

            ViewData["StaffNames"] = StaffNames;

            return View();
        }

        // GET: Leaves/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var leave = await _context.Leave
                .FirstOrDefaultAsync(m => m.Id == id);
            if (leave == null)
            {
                return NotFound();
            }

            return View(leave);
        }

        // GET: Leaves/Create
        public IActionResult Create()
        {
            ViewData["Staff"] = _context.Staff.Distinct()
                .OrderBy(n => n.FirstName)
                .Select(n => new SelectListItem
                {
                    Value = n.Id.ToString(),
                    Text = n.FirstName + " " + n.LastName
                }).ToList();

            return View();
        }

        // POST: Leaves/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Staff,StartDate,EndDate,TotalDays,Accepted")] Leave leave)
        {
            int staffid = leave.Staff.Id;
            Staff staff = _context.Staff.Where(s => s.Id == staffid).SingleOrDefault();

            leave.Staff = staff;
            // set leave accepted to false
            leave.Accepted = false;
            
            if (ModelState.IsValid)
            {
                _context.Add(leave);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(leave);
        }

        // GET: Leaves/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var leave = await _context.Leave.FindAsync(id);
            if (leave == null)
            {
                return NotFound();
            }

            int staffid = _context.Leave
                .Include(s => s.Staff)
                .Where(l => l.Id == id)
                .Select(s => s.Staff.Id)
                .SingleOrDefault();

            ViewData["StaffId"] = staffid;

           return View(leave);
        }

        // POST: Leaves/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,StartDate,EndDate,TotalDays,Accepted")] Leave leave)
        {
            if (id != leave.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (leave.Accepted == true)
                    {
                        int staffid = _context.Leave
                            .Include(s => s.Staff)
                            .Where(l => l.Id == id)
                            .Select(s => s.Staff.Id)
                            .SingleOrDefault();

                        Staff staff = (Staff)_context.Staff.Where(s => s.Id == staffid).SingleOrDefault();

                        Events events = new Events();
                        events.IsFullDay = true;
                        events.Start = leave.StartDate;
                        events.End = leave.EndDate;
                        events.Days = leave.TotalDays;
                        events.Staff = staff;
                        events.Title = staff.FirstName + " " + staff.LastName + " Annual Leave";

                        _context.Add(events);
                    }
                    _context.Update(leave);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LeaveExists(leave.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(leave);
        }

        // GET: Leaves/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var leave = await _context.Leave
                .FirstOrDefaultAsync(m => m.Id == id);
            if (leave == null)
            {
                return NotFound();
            }

            return View(leave);
        }

        // POST: Leaves/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var leave = await _context.Leave.FindAsync(id);
            _context.Leave.Remove(leave);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LeaveExists(int id)
        {
            return _context.Leave.Any(e => e.Id == id);
        }
    }
}

ProjectFinalEMDAAdvanced/Views/Leaves/Create.cshtml
@model ProjectFinalEMDAAdvanced.Models.Leave

@{
    ViewData["Title"] = "Create";
}

<div class="container">
    <div class="jumbotron">
        <h2>Create Leave Request</h2>
        <h4>For Annual Leave</h4>
        <div>
            ( <a asp-action="Index"><span class="glyphicon glyphicon-hand-left"></span> Back to List</a> )
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Staff" class="control-label"></label>
                    <select id="StaffSelect" asp-for="Staff.Id" asp-items="@((List<SelectListItem>) ViewData["Staff"])" class="form-control" style="width: 100%">
                        <option value="">Select Staff</option>
                    </select>
                    <span asp-validation-for="Staff" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="StartDate" class="control-label"></label>
                    <input asp-for="StartDate" class="form-control" />
                    <span asp-validation-for="StartDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="EndDate" class="control-label"></label>
                    <input asp-for="EndDate" class="form-control" />
                    <span asp-validation-for="EndDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="TotalDays" class="control-label"></label>
                    <input asp-for="TotalDays" class="form-control" />
                    <span asp-validation-for="TotalDays" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjectFinalEMDAAdvanced/Views/Leaves/Delete.cshtml
@model ProjectFinalEMDAAdvanced.Models.Leave

@{
    ViewData["Title"] = "Delete";
}

<div class="container">
    <div class="jumbotron">
        <h2>Delete Leave</h2>
        <h3>Are you sure you want to delete this?</h3>
    </div>
    <div>
        <h4>Leave</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.StartDate)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.StartDate)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.EndDate)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.EndDate)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.TotalDays)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.TotalDays)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Accepted)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Accepted)
            </dd>
        </dl>

        <form asp-action="Delete">
            <a asp-action="Index">Back to List</a> |
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="Delete" class="btn btn-danger" />
        </form>
    </div>
</div>

ProjectFinalEMDAAdvanced/Views/Leaves/Details.cshtml
@model ProjectFinalEMDAAdvanced.Models.Leave

@{
    ViewData["Title"] = "Details";
}

<div class="container">
    <div class="jumbotron">
        <h2>Details For Leave</h2>
        <div>
            <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
            <a asp-action="Index">Back to List</a>
        </div>
    </div>

    <div>
        <h4>Annual Leave Dates</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.StartDate)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.StartDate)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.EndDate)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.EndDate)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.TotalDays)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.TotalDays)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Accepted)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Accepted)
            </dd>
        </dl>
    </div>
</div>

ProjectFinalEMDAAdvanced/Views/Leaves/Edit.cshtml
@model ProjectFinalEMDAAdvanced.Models.Leave

@{
    ViewData["Title"] = "Edit";
}

<div class="container">
    <h2>Edit</h2>

    <h4>Leave</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <input type="hidden" asp-for="Staff.Id" value="@ViewData["StaffId"]" />
                <div class="form-group">
                    <label asp-for="StartDate" class="control-label"></label>
                    <input asp-for="StartDate" class="form-control" />
                    <span asp-validation-for="StartDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="EndDate" class="control-label"></label>
                    <input asp-for="EndDate" class="form-control" />
                    <span asp-validation-for="EndDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="TotalDays" class="control-label"></label>
                    <input asp-for="TotalDays" class="form-control" />
                    <span asp-validation-for="TotalDays" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <div class="checkbox">
                        <label>
                            <input asp-for="Accepted" /> @Html.DisplayNameFor(model => model.Accepted)
                        </label>
                    </div>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjectFinalEMDAAdvanced/Views/Leaves/Index.cshtml
@model IEnumerable<ProjectFinalEMDAAdvanced.Models.Leave>

@{
    ViewData["Title"] = "Index";
}

<div class="container">
    <div class="jumbotron">
        <div class="row">
            <div class="col-xs-7">
                <h2>Annual Leave</h2>
                <a class="label label-danger" asp-controller="Events" asp-action="Index" style="margin-top: 20px">Click Here To Remove An Event From The Calendar</a>
            </div>
            <div class="col-xs-5 text-right">
                <a class="btn btn-info" asp-action="Create" style="margin-top: 20px">Create New Request</a>
            </div>
        </div>
    </div>
    <div id="script-warning"></div>
    <div class="row">
        <div class="col-md-8 col-md-offset-2" id="calendar"></div>
    </div>
    <div class="table-responsive">
        <table class="table">
            <thead>
            <tr>
                <th>
                    Staff Member
                </th>
                <th>
                    Start Date
                </th>
                <th>
                    End Date
                </th>
                <th>
                    # of Days
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Accepted)
                </th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            @foreach (var item in ViewData["StaffNames"] as List<Leave>)
            {
                <tr>
                    <td>
                        @item.Staff.FirstName @item.Staff.LastName
                    </td>
                    <td>
                        @item.StartDate.ToShortDateString()
                    </td>
                    <td>
                        @item.EndDate.ToShortDateString()
                    </td>
                    <td>
                        @item.TotalDays
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.Accepted)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id"><span class="glyphicon glyphicon-edit"></span> Edit</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
                        <a asp-action="Delete" asp-route-id="@item.Id" style="color: red">Delete <span class="glyphicon glyphicon-trash"></span></a>
                    </td>
                </tr>
            }
            </tbody>
        </table>
    </div>
</div>

@section Scripts
{
<script type="text/javascript">
    $(document).ready(function () {
        $('#calendar').fullCalendar({
            themeSystem: 'bootstrap4',
            defaultView: 'month',
            fixedWeekCount: false,
            events: {
                url: '/api/EventsAPI',
                error: function () {
                    $('#script-warning').show();
                }
            }
        });
    });
</script>
}