ProjectFinalEMDAAdvanced/Controllers/LeavesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjectFinalEMDAAdvanced.Data;
using ProjectFinalEMDAAdvanced.Models;

namespace ProjectFinalEMDAAdvanced.Controllers
{
    [Authorize]
    public class LeavesController : Controller
    {
        private readonly StaffDbContext _context;

        public LeavesController(StaffDbContext context)
        {
            _context = context;
        }

        // GET: Leaves
        public async Task<IActionResult> Index()
        {
            List<Leave> StaffNames = new List<Leave>();
            StaffNames.AddRange(_context.Leave
                .Include(s => s.Staff)
                .ToList());

            ViewData["StaffNames"] = StaffNames;

            return View();
        }

        // GET: Leaves/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var leave = await _context.Leave
                .FirstOrDefaultAsync(m => m.Id == id);
            if (leave == null)
            {
                return NotFound();
            }

            return View(leave);
        }

        // GET: Leaves/Create
        public IActionResult Create()
        {
            ViewData["Staff"] = _context.Staff.Distinct()
                .OrderBy(n => n.FirstName)
                .Select(n => new SelectListItem
                {
                    Value = n.Id.ToString(),
                    Text = n.FirstName + " " + n.LastName
                }).ToList();

            return View();
        }

        // POST: Leaves/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Staff,StartDate,EndDate,TotalDays,Accepted")] Leave leave)
        {
            int staffid = leave.Staff.Id;
            Staff staff = _context.Staff.Where(s => s.Id == staffid).SingleOrDefault();

            leave.Staff = staff;
            // set leave accepted to false
            leave.Accepted = false;
            
            if (ModelState.IsValid)
            {
                _context.Add(leave);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(leave);
        }

        // GET: Leaves/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var leave = await _context.Leave.FindAsync(id);
            if (leave == null)
            {
                return NotFound();
            }

            int staffid = _context.Leave
                .Include(s => s.Staff)
                .Where(l => l.Id == id)
                .Select(s => s.Staff.Id)
                .SingleOrDefault();

            ViewData["StaffId"] = staffid;

           return View(leave);
        }

        // POST: Leaves/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,StartDate,EndDate,TotalDays,Accepted")] Leave leave)
        {
            if (id != leave.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (leave.Accepted == true)
                    {
                        int staffid = _context.Leave
                            .Include(s => s.Staff)
                            .Where(l => l.Id == id)
                            .Select(s => s.Staff.Id)
                            .SingleOrDefault();

                        Staff staff = (Staff)_context.Staff.Where(s => s.Id == staffid).SingleOrDefault();

                        Events events = new Events();
                        events.IsFullDay = true;
                        events.Start = leave.StartDate;
                        events.End = leave.EndDate;
                        events.Days = leave.TotalDays;
                        events.Staff = staff;
                        events.Title = staff.FirstName + " " + staff.LastName + " Annual Leave";

                        _context.Add(events);
                    }
                    _context.Update(leave);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LeaveExists(leave.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(leave);
        }

        // GET: Leaves/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var leave = await _context.Leave
                .FirstOrDefaultAsync(m => m.Id == id);
            if (leave == null)
            {
                return NotFound();
            }

            return View(leave);
        }

        // POST: Leaves/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var leave = await _context.Leave.FindAsync(id);
            _context.Leave.Remove(leave);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LeaveExists(int id)
        {
            return _context.Leave.Any(e => e.Id == id);
        }
    }
}

ProjectFinalEMDAAdvanced/Controllers/StaffsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjectFinalEMDAAdvanced.Data;
using ProjectFinalEMDAAdvanced.Models;
using ProjectFinalEMDAAdvanced.ViewModels;

namespace ProjectFinalEMDAAdvanced.Controllers
{
    [Authorize]
    public class StaffsController : Controller
    {
        private readonly StaffDbContext _context;

        public StaffsController(StaffDbContext context)
        {
            _context = context;
        }

        // GET: Staffs
        public async Task<IActionResult> Index()
        {
            return View(await _context.Staff.ToListAsync());
        }

        // GET: Staffs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var staff = await _context.Staff
                .FirstOrDefaultAsync(m => m.Id == id);
            if (staff == null)
            {
                return NotFound();
            }

            return View(staff);
        }

        // GET: Staffs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Staffs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,In,TimeIn")] Staff staff)
        {
            staff.In = true;
            staff.TimeIn = DateTime.Now;
            staff.TimeOut = DateTime.Today;
            
            if (ModelState.IsValid)
            {
                _context.Add(staff);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(staff);
        }

        // GET: Staffs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            ViewData["Reasons"] = _context.Reasons.Distinct()
               .OrderByDescending(n => n.ReasonCount)
               .Select(n => new SelectListItem()
               {
                   Value = n.Id.ToString(),
                   Text = n.Reason
               }).ToList();

            if (id == null)
            {
                return NotFound();
            }

            var staff = await _context.Staff.FindAsync(id);
            if (staff == null)
            {
                return NotFound();
            }
            return View(staff);
        }

        // POST: Staffs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,In")] Staff staff)
        {
            if (id != staff.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (staff.In == true)
                    {
                        staff.TimeIn = DateTime.Now;
                        _context.Update(staff);
                    }
                    else if (staff.In == false)
                    {
                        staff.TimeOut = DateTime.Now;
                        _context.Update(staff);

                        //update sign outs table
                        
                        SignOuts signOuts = new SignOuts();
                        signOuts.Day = DateTime.Now;
                        signOuts.TimeOut = DateTime.Now;
                        // do a calculation
                        if (staff.TimeIn.Date == DateTime.Today.Date)
                        {
                            string hours = (DateTime.Now.TimeOfDay - staff.TimeIn.TimeOfDay).ToString();
                            signOuts.HoursIn = hours;
                        }
                        else
                        {
                            string hours = "n/a";
                            signOuts.HoursIn = hours;
                        }
                        int staffid = id;
                        Staff staffSelected = _context.Staff.Where(s => s.Id == staffid).SingleOrDefault();
                        signOuts.Staff = staffSelected;
                        int reasonid = 999;
                        Reasons reasonSelected = _context.Reasons.Where(r => r.Id == reasonid).SingleOrDefault();
                        signOuts.Reason = reasonSelected;

                        // update sign outs table
                        _context.Add(signOuts);
                        await _context.SaveChangesAsync();
                    }
                    
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StaffExists(staff.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(staff);
        }

        // GET: Staffs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var staff = await _context.Staff
                .FirstOrDefaultAsync(m => m.Id == id);
            if (staff == null)
            {
                return NotFound();
            }

            return View(staff);
        }

        // POST: Staffs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var staff = await _context.Staff.FindAsync(id);
            _context.Staff.Remove(staff);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StaffExists(int id)
        {
            return _context.Staff.Any(e => e.Id == id);
        }
    }
}

ProjectFinalEMDAAdvanced/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EMDA</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link href='https://fonts.googleapis.com/css?family=Allerta Stencil' rel='stylesheet'>
        <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
        <link href="~/css/bootstrap.min.css" rel="stylesheet" />
        <link href="~/css/plugins.css" rel="stylesheet" />
        <link href="~/css/lora-web-font.css" rel="stylesheet" />
        <link href="~/css/opensans-web-font.css" rel="stylesheet" />
        <link href="~/css/magnific-popup.css" rel="stylesheet" />
        <link href="~/css/style.css" rel="stylesheet" />
        <link href="~/css/responsive.css" rel="stylesheet" />
        <link href="~/css/fullcalendar.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand"><img src="~/images/emda_logo.png" style="width: 75px;"/></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Staffs" asp-action="Index">Staff</a></li>
                    <li><a asp-area="" asp-controller="Reasons" asp-action="Index">Reasons</a></li>
                    <li><a asp-area="" asp-controller="Leaves" asp-action="Index">Annual Leave</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="body-content">
        @RenderBody()
        <footer>
            <p class="container">&copy; 2021 - Balraj Singh</p>
            <img src="~/images/crusaders.jpg" class="img-responsive" />
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/vendor/modernizr-2.8.3-respond-1.4.2.min.js"></script>
        <script src="~/js/vendor/isotope.min.js"></script>
        <script src="~/js/plugins.js"></script>
        <script src="~/js/jquery.magnific-popup.js"></script>
        <script src="~/js/main.js"></script>
        <script src="~/lib/moment.min.js"></script>
        <script src="~/js/fullcalendar.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>