ProjectFinalEMDAAdvanced/Models/SignOuts.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ProjectFinalEMDAAdvanced.Models
{
    public class SignOuts
    {
        [Key]//primary key
        public int Id { get; set; }
        public Staff Staff { get; set; }//Staff
        public DateTime Day { get; set; }//Day
        public DateTime TimeOut { get; set; }//Timeout
        public Reasons Reason { get; set; }//Reasons
        public string HoursIn { get; set; }//HoursIn
    }
}

ProjectFinalEMDAAdvanced/Controllers/SignOutsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjectFinalEMDAAdvanced.Business;
using ProjectFinalEMDAAdvanced.Data;
using ProjectFinalEMDAAdvanced.Models;
using ProjectFinalEMDAAdvanced.ViewModels;

namespace ProjectFinalEMDAAdvanced.Controllers
{
    [Authorize]
    public class SignOutsController : Controller
    {
        private readonly StaffDbContext _context;
        private readonly IDbCalls _dbcalls;

        public SignOutsController(StaffDbContext context, IDbCalls dbCalls)
        {
            _context = context;
            _dbcalls = dbCalls;
        }

        // GET: SignOuts
        public async Task<IActionResult> Index()
        {
            return View();
        }

        // GET: SignOuts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var signOuts = await _context.SignOuts
                .FirstOrDefaultAsync(m => m.Id == id);
            if (signOuts == null)
            {
                return NotFound();
            }

            return View(signOuts);
        }

        // GET: SignOuts/Create
        public IActionResult Create()
        {
            ViewData["Staff"] = _context.Staff.Distinct()
                .OrderBy(n => n.FirstName)
                .Select(n => new SelectListItem
                {
                    Value = n.Id.ToString(),
                    Text = n.FirstName + " " + n.LastName
                }).ToList();

            ViewData["StaffIn"] = _context.Staff.Distinct()
                .OrderBy(n => n.Id)
                .Select(n => new SelectListItem()
                {
                    Value = n.Id.ToString(),
                    Text = n.In.ToString()
                }).ToList();

            ViewData["Reasons"] = _context.Reasons.Distinct()
                .OrderByDescending(n => n.ReasonCount)
                .Select(n => new SelectListItem()
                {
                    Value = n.Id.ToString(),
                    Text = n.Reason
                }).ToList();

            return View();
        }

        // POST: SignOuts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Day,TimeOut,HoursIn,Reason,Staff,StaffIn")] CreateSignOutVM createSignOutVM)
        {
            // staff is signing in
            if (createSignOutVM.StaffIn == true)
            {
                int staffid = createSignOutVM.Staff.Id;
                Staff staff = (Staff)_context.Staff.Where(s => s.Id == staffid).SingleOrDefault();

                staff.In = true;
                staff.TimeIn = DateTime.Now;

                _context.Update(staff);
                await _context.SaveChangesAsync();
                return Redirect("~/Home/Index#UpdateStatus");
            }
            // staff is signing out
            if (ModelState.IsValid)
            {
                int reasonid = createSignOutVM.Reason.Id;
                Reasons reason = (Reasons)_context.Reasons.Where(r => r.Id == reasonid).SingleOrDefault();
                int staffid = createSignOutVM.Staff.Id;
                Staff staff = (Staff)_context.Staff.Where(s => s.Id == staffid).SingleOrDefault();

                // increment reason count
                if (reasonid != 999)
                {
                    _dbcalls.IncrementReasonCount(reasonid);
                }
                
                SignOuts signOuts = new SignOuts();
                signOuts.Day = DateTime.Now;
                signOuts.TimeOut = DateTime.Now;
                // do a calculation
                if (staff.TimeIn.Date == DateTime.Today.Date)
                {
                    string hours = (DateTime.Now.TimeOfDay - staff.TimeIn.TimeOfDay).ToString();
                    signOuts.HoursIn = hours;
                }
                else
                {
                    string hours = "n/a";
                    signOuts.HoursIn = hours;
                }
                signOuts.Staff = staff;
                signOuts.Reason = reason;
                    
                // update sign outs table
                _context.Add(signOuts);
                await _context.SaveChangesAsync();
                    
                // update the staff table 'In' field and time field
                staff.In = false;
                staff.TimeOut = DateTime.Now;
                    
                _context.Update(staff);
                await _context.SaveChangesAsync();
                return Redirect("~/Home/Index#UpdateStatus");
            }
            return NotFound();
        }

        // GET: SignOuts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var signOuts = await _context.SignOuts.FindAsync(id);
            if (signOuts == null)
            {
                return NotFound();
            }
            return View(signOuts);
        }

        // POST: SignOuts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Day,TimeOut,HoursIn")] SignOuts signOuts)
        {
            if (id != signOuts.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(signOuts);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SignOutsExists(signOuts.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(signOuts);
        }

        // GET: SignOuts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var signOuts = await _context.SignOuts
                .FirstOrDefaultAsync(m => m.Id == id);
            if (signOuts == null)
            {
                return NotFound();
            }

            return View(signOuts);
        }

        // POST: SignOuts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var signOuts = await _context.SignOuts.FindAsync(id);
            _context.SignOuts.Remove(signOuts);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SignOutsExists(int id)
        {
            return _context.SignOuts.Any(e => e.Id == id);
        }
    }
}

ProjectFinalEMDAAdvanced/Views/SignOuts/Create.cshtml
@model ProjectFinalEMDAAdvanced.ViewModels.CreateSignOutVM

<div class="container">
    <h2>
        Sign In / Out
    </h2>
    <br />
    <div class="row">
        <form name="staffform" asp-controller="SignOuts" asp-action="Create">
            <div class="col-md-4 col-xs-12 margin-bottom-20">
                <select id="StaffSelect" asp-for="Staff.Id" asp-items="@((List<SelectListItem>) ViewData["Staff"])" class="form-control" style="width: 100%">
                    <option value="">Select Staff</option>
                </select>
            </div>
            <div class="col-md-2 col-xs-12 text-center margin-bottom-20">
                <input asp-for="StaffIn" id="InToggle" type="checkbox" data-toggle="toggle" data-on="In" data-off="Out" data-style="ios" />
            </div>
            <div class="col-md-4 col-xs-12 margin-bottom-20">
                <select asp-for="Reason.Id" id="ReasonSelect" asp-items="@((List<SelectListItem>) ViewData["Reasons"])" class="form-control" style="width: 100%; display:none">
                    <option value="">Select Reason</option>
                </select>
            </div>
            <div class="col-md-2 col-xs-12">
                <input type="submit" class="btn btn-primary" style="width: 95%; margin: auto;" />
            </div>
        </form>
    </div>
</div>

@*@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}*@

ProjectFinalEMDAAdvanced/Views/SignOuts/Delete.cshtml
@model ProjectFinalEMDAAdvanced.Models.SignOuts

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SignOuts</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Day)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Day)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TimeOut)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TimeOut)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.HoursIn)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HoursIn)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ProjectFinalEMDAAdvanced/Views/SignOuts/Details.cshtml
@model ProjectFinalEMDAAdvanced.Models.SignOuts

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>SignOuts</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Day)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Day)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TimeOut)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TimeOut)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.HoursIn)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HoursIn)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ProjectFinalEMDAAdvanced/Views/SignOuts/Edit.cshtml
@model ProjectFinalEMDAAdvanced.Models.SignOuts

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>SignOuts</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Day" class="control-label"></label>
                <input asp-for="Day" class="form-control" />
                <span asp-validation-for="Day" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TimeOut" class="control-label"></label>
                <input asp-for="TimeOut" class="form-control" />
                <span asp-validation-for="TimeOut" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HoursIn" class="control-label"></label>
                <input asp-for="HoursIn" class="form-control" />
                <span asp-validation-for="HoursIn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjectFinalEMDAAdvanced/Views/SignOuts/Index.cshtml
@using System.Collections
@*@model List<SignOuts>*@
@model List<Staff>

@{
    ViewData["Title"] = "Index";
}
<div class="container">
    <div class="col-md-3">
        <h3>Staff Status</h3>
        @foreach (var staff in (IEnumerable) ViewData["StaffStatus"] as List<Staff>)
        {
            if (staff.In)
            {
                <span style="color: greenyellow; font-weight: bold; font-size: 18px;">@staff.FirstName @staff.LastName</span><br/>
            }
            else
            {
                <span style="color: red; font-size: 18px;">@staff.FirstName @staff.LastName</span><br/>
            }
        }
    </div>
    <div class="col-md-9">
        <h3 class="col-xs-12">Sign Outs Today: </h3>

        @foreach (var item in ViewData["StaffOut"] as List<SignOuts>)
        {
            if (item.Day.Date == DateTime.Today.Date)
            {
                 <p class="col-md-4">
                     <b>@item.Staff.FirstName @item.Staff.LastName </b>
                     <br />
                     Signed out at:
                     @item.TimeOut.ToShortTimeString()
                     <br/>Reason:
                     @item.Reason.Reason
                     <br/>Hours in office:
                     @if (item.HoursIn.Length > 3)
                     {
                         @item.HoursIn.Substring(0, 5)
                     }
                     else
                     {
                         @item.HoursIn.Substring(0, 3)
                     }
                 </p>
             }
        }

        <h3 class="col-xs-12">Past: </h3>

        @foreach (var item in ViewData["StaffOut"] as List<SignOuts>)
        {
            @if (item.Day.Date != DateTime.Today.Date)
             {
                 <p class="col-md-4">
                     <b>@item.Staff.FirstName @item.Staff.LastName </b>
                     <br />
                     Signed out at:
                     @item.TimeOut.ToShortTimeString()
                     <br/>Reason:
                     @item.Reason.Reason
                     <br/>Hours in office:
                     @if (item.HoursIn.Length > 3)
                     {
                         @item.HoursIn.Substring(0, 5)
                     }
                     else
                     {
                         @item.HoursIn.Substring(0, 3)
                     }
                 </p>
             }
        }
    </div>

</div>